name: Update badges

on:
  schedule:
    # Runs at 2am UTC
    - cron: "0 2 * * *"
jobs:
  update-readme:
    name: Update Readme with badges
    runs-on: ubuntu-latest
    steps:
      - name: Badges - Readme
        uses: wy-chan/badge-readme@main
        with:       
          CREDLY_USER: wing-yu-chan # optional, but default will use the same from github
